spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json
  api-docs:
    path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html #http://localhost:8088/api/v1/swagger-ui/index.html

server:
  servlet:
      context-path: /api/v1/
